letters.register_letters("default", "clay", "default:clay", "Clay", "default_clay.png")
letters.register_letters("default", "stonebrick", "default:stonebrick", "Stone brick", "default_stone_brick.png")
letters.register_letters("default", "pine_wood", "default:pine_wood", "Pine wood", "default_pine_wood.png")
letters.register_letters("default", "acacia_wood", "default:acacia_wood", "Acacia wood", "default_acacia_wood.png")
letters.register_letters("default", "aspen_wood", "default:aspen_wood", "Aspen wood", "default_aspen_wood.png")
